package szympan.jaz.entity;

public enum Province {
    
    POMORSKIE, PODKARPACKIE, MAZOWIECKIE, LUBUSKIE, LUBELSKIE,
    DOLNOSLASKIE, ZACHODNIO_POMORSKIE, WARMINSKO_MAZURSKIE, 
    KUJAWSKO_POMORSKIE, SWIETOKRZYSKIE, SLASKIE, LODZKIE,
    WIELKOPOLSKIE, PODLASKIE, MALOPOLSKIE, OPOLSKIE
    
}
